import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Provider } from "react-redux";
import { configureStore } from "@reduxjs/toolkit";
import cartReducer from "@/app/store/cartSlice";

const store = configureStore({
  reducer: {
    cart: cartReducer,
  },
});
export type RootState = ReturnType<typeof store.getState>;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <Provider store={store}> */}
        <Navbar />
        {children}
        {/* </Provider> */}
      </body>
    </html>
  );
}
